apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bootcampapp-yr7a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bootcampapp-yr7a
    app.kubernetes.io/part-of: nodevfiletest
  name: bootcampapp-yr7a
  namespace: utherp0-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: bootcampapp-yr7a
    weight: null
status: {}
